services:
  # PHP (artisan / fpm)
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: runtime          # php を含むステージを最終に
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    # php-fpm ポートは内部通信のみで可
    expose:
      - "9000"

  # Web (nginx)
  web:
    image: nginx:1.27-alpine
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "9000:80"

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: dev 
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000" 

  db:
    build: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: