name: CI
on: [push, pull_request]
jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: contents_meet_test
        ports: ["3306:3306"]
    steps:
      - uses: actions/checkout@v4

      # PHP 8.4 + Composer をセットアップ
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      # ① backend ディレクトリで Composer
      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --ansi
        working-directory: backend

      # ② .env と APP_KEY
      - name: Prepare .env
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: backend

      # ③ マイグレーション
      - name: Run migrations
        run: php artisan migrate --force
        working-directory: backend

      # ④ テスト実行
      - name: PHPUnit
        run: php artisan test --colors=always
        working-directory: backend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: '21'}
      - run: cd frontend && npm ci && npm run lint