name: CI
on: [push, pull_request]
jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env: {MYSQL_ROOT_PASSWORD: secret}
        ports: ["3306:3306"]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: {php-version: '8.4'}
      - run: composer install -q --working-dir=backend
      - run: php backend/artisan test
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: '21'}
      - run: cd frontend && npm ci && npm run lint